In [1]:
import snowflake.connector
print(snowflake.connector.__version__)

3.18.0

In [2]:
import sys
import os
import datetime as dt
from datetime import datetime, timedelta, date
import gspread
import gspread_dataframe
from gspread_dataframe import get_as_dataframe, set_with_dataframe
import pandas as pd
import sql_explorer as exp
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import json
import pytz
import warnings
warnings.filterwarnings('ignore')
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
def query_execute(query):
    """
    Executes the given SQL query. Tries first with SCM schema, falls back to PUBLIC if SCM fails.
    """
    def run_query(schema):
        conn = snowflake.connector.connect(
            user='SHUVENDU_PRITAM',
            password='@SnowFlake(20@2)',
            account='yf90836.ap-south-1.aws',
            warehouse='COMPUTE_WH',
            database='WAKEFIT_DB',
            schema=schema
        )
        cursor = conn.cursor()
        try:
            cursor.execute(query)
            data = cursor.fetchall()
            df = pd.DataFrame(data, columns=[desc[0].lower() for desc in cursor.description])
            print(f"Query executed in schema: {schema}")
            return df
        finally:
            cursor.close()
            conn.close()
    # Try SCM schema first
    try:
        return run_query('SCM')
    except Exception as e:
        print(f"Failed in SCM: {e}")
        print("Trying in PUBLIC schema...")
        try:
            return run_query('PUBLIC')
        except Exception as e:
            print(f"Failed in PUBLIC: {e}")
            print("Trying in CRM schema...")
            return run_query('CRM')

    
playground_id = 'shuvendu.pritam@wakefit.co'
playground_password = 'qkkefrQs3c'

In [4]:
credentials = {
  "type": "service_account",
  "project_id": "pexanalytics",
  "private_key_id": "c1f0f45e3821f94efb0b8998d3b07d8b43636af3",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsS7ncddhr5jKa\nK0X9CNB0Wbvy5nmOta1wffRtDI1U3vY8TnMo3bk66IlvL22MDesDJ7+v8s3e3zP6\npxpPcAEZiGEgwPBQGWRmaCDfGG8Q4uFM2TSjMRyDWqKab3I1rmgXjRhezt1PjuNf\nQFbR6VkBz5GRkmAdntMwl/7ucIZ6yqt24pIpidMyOI4Kdz07Y+LxJyq8rzMEEjcy\nfAQSxXL8D09qcb8BdfoQJYzF2kr16ssH1pXg21QJahFfJBMQ1Xz+OdcO+GPupWKu\nYBg6ltA67oPf3vjcUXjv2ippnSa7kzmdOOdow77PHjfdMKG52PyonQRTIsTC+Gl5\nxMa807W1AgMBAAECggEAHxASBLisWZupgNkPZ7S4nFl3RK4fuUZw7AiRUj3Cl0wR\nWcMNCQ+cbw3whT6oQeladvmqGgcs7aMRJH4PBMZdNGS9miGe0doaG0pnrsEheQpm\ncyvvzQI0MUxcZ3pzPVFhy+kwvRsPlGHfBVO8s2CeHvD0vimFMaHqUmb827Em1ak7\nrQkKlIiQ4S2EFQ8Cndhf5mBAEiksHxyCZaeNmPA8rdxf5mQcMhfURLSfpR86Zk90\nud53bm3AjI3GIX7D64XpyeEaEoExQpygXbiglFkJL+1FGdXlzvQuKAdIW14mg2ZF\notVfswZT7B8GB1vqsXkt+L1iNGzP0Cxpjk9xIpWg4QKBgQDWWqHB7Zj1eMkibm0U\nNhdnH1T4I888gX4OYDD8TEWfEnCHzkEhqyza8Pp/2ARHfYAQmSwLeuZ+yXoE+TjT\nGEbFztCyWQv223omQtbDTvvdcxQ+u+dFOVXeZpv8uzFiZb30Thr/+L0MUUgBb8v0\nEgk0mB/ZVfwlQ/GSwxI/NAJwZQKBgQDNxTxpoYrlEyiFpqd8xof/ASt8e1EItu7S\nkxfWgYym2uWO8lMd1h3/W6Q+vCLJxZMEJ/xsJ3difJuLldCc4ZsBKLJNHcPfHtl9\nLG7cEL0zx+WZ3WkqcqfydD0TcKOPhbAnw7m3uCzELu2//Xy6GvMviMjDbWeH028w\ns1FFF/vTEQKBgQDMh1wTE6fAiYi5fs4728UG06Gax2hlHlXuV6BGDGzd9JVFL+t7\nub4qBoeu1qp2oGxC6jRZm+I1Ff+EoVy0J1TYR5dgpZDB8feibGJJp6KxUa3+kgKB\nTcz+UcADLYZYkiXm52Ph3DBegWwIWukrsM3xzjmNgfr+f88QL2vIvNKa9QKBgCAa\nosdURehhqdPYYY9NJlC57P/5+XWjnPVLr89u3PP3eRNpaWBhVMLPmHuVPNRAOCTQ\n3Eg/jBfYmygXEro3VMjEgbUYbMP1+zbVZOJ+1hYrHP55lfvicaOZUSIkU9CDqi06\nE1K/sHRXYg6vTPN4WvLSo4giHKILcfCmOYrPKCIRAoGATY9SdhT1pBaEhY3dzdrM\n0zMj6e9Oj+GZjPwh5TIrNRTepcwIT5HWPZzoCc6jTIuPWYMsmHa/OtRZeif1oEbj\nba/lyd0P+RPH9dqbIbCQ4YWKO3xq+yqd4z4rPq+nCC0W3Q8axESOEk209GGk7Yu3\njl0pC0PKVaBWtXYREsY1b48=\n-----END PRIVATE KEY-----\n",
  "client_email": "pex-analytics@pexanalytics.iam.gserviceaccount.com",
  "client_id": "115540536484257911435",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/pex-analytics%40pexanalytics.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
gc=gspread.service_account_from_dict(credentials)

In [5]:
def read_sheet(sheet_key, tab_name):
    gc = gspread.service_account_from_dict(credentials)
    master = gc.open_by_key(sheet_key)
    wks_in = master.worksheet(tab_name)
    df = get_as_dataframe(wks_in, evaluate_formulas=True, skiprows=0)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    return df

def write_sheet(sheet_key, tab_name, df):
    gc = gspread.service_account_from_dict(credentials)
    master = gc.open_by_key(sheet_key)
    wks_out = master.worksheet(tab_name)
    set_with_dataframe(wks_out, df)
    print(' Written to sheet:', tab_name)

def clean_sheet(sheet_key, tab_name, range_string="A:AAZ"):
    gc = gspread.service_account_from_dict(credentials)
    master = gc.open_by_key(sheet_key)
    full_range = f"{tab_name}!{range_string}"
    master.values_clear(full_range)
    print(' Sheet cleared:', full_range)

def read_sheet_skip_row_1(sheet_key, tab_name):
    gc = gspread.service_account_from_dict(credentials)
    master = gc.open_by_key(sheet_key)
    wks_in = master.worksheet(tab_name)
    df = get_as_dataframe(wks_in, evaluate_formulas=True, skiprows=1)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    return df

In [6]:
# https://docs.google.com/spreadsheets/d/1LiCjKQ_7pSLM_4Db4ALSAClRmy0-WoU1Wl_lksZJaF8/edit?gid=0#gid=0
sheet_key = '1LiCjKQ_7pSLM_4Db4ALSAClRmy0-WoU1Wl_lksZJaF8'
tab_name = 'output'

In [7]:
df_sto = read_sheet(sheet_key, tab_name)
df_sto.head(5)

,date,warehouse_id,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm
0,2026-08-17,1.0,furniture,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31
1,2026-08-17,1.0,sofa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31
2,2026-08-17,1.0,office chair,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31
3,2026-08-17,1.0,mattress,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31
4,2026-08-17,1.0,bean bags,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31

In [8]:
master_warehouse = '''
select id, warehouse_code, plant_code from wakefit_db.crm.wf_master_warehouse
'''
df_master_warehouse = query_execute(master_warehouse)

Query executed in schema: SCM

In [9]:
# map warehouse_code / plant_code into df_sto  :  df_sto.warehouse_id -> df_master_warehouse.id
wh_map = df_master_warehouse.copy()
wh_map['id'] = pd.to_numeric(wh_map['id'], errors='coerce')
wh_map = wh_map.dropna(subset=['id']).drop_duplicates(subset=['id']).set_index('id')

df_sto['warehouse_id'] = pd.to_numeric(df_sto['warehouse_id'], errors='coerce')
df_sto['warehouse_code'] = df_sto['warehouse_id'].map(wh_map['warehouse_code'])
df_sto['plant_code'] = df_sto['warehouse_id'].map(wh_map['plant_code'])

# keep the two new columns beside warehouse_id
cols = list(df_sto.columns)
for c in ['plant_code', 'warehouse_code']:
    cols.insert(cols.index('warehouse_id') + 1, cols.pop(cols.index(c)))
df_sto = df_sto[cols]

unmapped = sorted(df_sto.loc[df_sto['warehouse_code'].isna(), 'warehouse_id'].dropna().unique())
print('rows:', len(df_sto),
      '| mapped:', int(df_sto['warehouse_code'].notna().sum()),
      '| unmapped warehouse_ids:', unmapped)
df_sto.head(5)

rows: 45600 | mapped: 45600 | unmapped warehouse_ids: []

,date,warehouse_id,warehouse_code,plant_code,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm
0,2026-08-17,1.0,BLR,XXX1,furniture,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31
1,2026-08-17,1.0,BLR,XXX1,sofa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31
2,2026-08-17,1.0,BLR,XXX1,office chair,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31
3,2026-08-17,1.0,BLR,XXX1,mattress,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31
4,2026-08-17,1.0,BLR,XXX1,bean bags,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-08-17 14:26:31

In [10]:
sheet_key = '1sAURSGD1-eptSOWWZluWLIQa6S93Ni_zchpDvuY3lcI'
tab_name = 'input_config'
input_config = read_sheet(sheet_key, tab_name)
input_config.head(5)

,warehouse_code,warehouse_code_all,no_of_days_demand,no_of_days_allocation,no_of_days_allocation_wise_speed,sto_run_time
0,AMD2,AMD2,60.0,60.0,60.0,4.0
1,BBR,BBR,NaN,NaN,NaN,5.0
2,BLR10,BLR10,NaN,NaN,NaN,6.0
3,BLR12,BLR12,NaN,NaN,NaN,NaN
4,BLR15,BLR15,NaN,NaN,NaN,NaN

In [11]:
# df_sto_filtered : keep only the warehouses listed in input_config.warehouse_code
def norm_code(s):
    return s.astype('string').str.strip().str.upper()

# config codes -> drop the blank / NaN rows that come from reading the whole sheet grid
cfg_key = norm_code(input_config['warehouse_code']).dropna()
cfg_key = cfg_key[cfg_key != '']
cfg_set = set(cfg_key)

sto_key = norm_code(df_sto['warehouse_code'])
df_sto_filtered = df_sto[sto_key.isin(cfg_set).fillna(False)].copy().reset_index(drop=True)

# reconciliation
sto_set = set(sto_key.dropna())
missing_in_sto = sorted(cfg_set - sto_set)
dropped_codes = sorted(sto_set - cfg_set)

print('config warehouses:', len(cfg_set))
print('df_sto rows:', len(df_sto), '-> df_sto_filtered rows:', len(df_sto_filtered))
print('warehouses kept:', df_sto_filtered['warehouse_code'].nunique())
print('in config but NOT in df_sto :', missing_in_sto)
print('in df_sto but NOT in config (dropped):', dropped_codes)
df_sto_filtered.head(5)

config warehouses: 45
df_sto rows: 45600 -> df_sto_filtered rows: 21120
warehouses kept: 44
in config but NOT in df_sto : ['MAN_RETAIL_1']
in df_sto but NOT in config (dropped): ['AMD', 'ANT', 'BLR', 'BLR1', 'BLR11', 'BLR13', 'BLR2', 'BLR3', 'BLR4', 'BLR5', 'BLR6', 'BLR9', 'BPL', 'CHN', 'CHN1', 'DEL', 'DWK', 'FBD2', 'GRG', 'GRG1', 'GRG2', 'GRG3', 'GRG4', 'HSR10', 'HSR11', 'HSR12', 'HSR13', 'HSR15', 'HSR3', 'HSR4', 'HSR7', 'HSR8', 'HSR9', 'HYD', 'HYD1', 'HYD2', 'HYD_2', 'JDH', 'JDH1', 'JDH2', 'KOL', 'LUK1', 'MBD', 'OKL', 'PUN', 'PUN1', 'PUN2', 'RJA', 'RJM', 'RNC', 'TRV']

,date,warehouse_id,warehouse_code,plant_code,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm
0,2026-08-17,3.0,MUM,MH01,furniture,284.0,57.880000,144.700000,428.700000,1641.0,659.0,1.0,711.0,783.0,1212.300000,0.0,0.0,0.0,2026-08-17 14:26:31
1,2026-08-17,3.0,MUM,MH01,sofa,120.0,8.952381,24.000000,144.000000,346.0,87.0,1.0,62.0,135.0,202.000000,0.0,0.0,0.0,2026-08-17 14:26:31
2,2026-08-17,3.0,MUM,MH01,office chair,87.0,30.328333,30.328333,117.328333,146.0,195.0,1.0,118.0,299.0,146.671667,153.0,153.0,118.0,2026-08-17 14:26:31
3,2026-08-17,3.0,MUM,MH01,mattress,186.0,83.271824,83.271824,269.271824,650.0,914.0,1.0,495.0,1974.0,875.728176,1324.0,1324.0,495.0,2026-08-17 14:26:31
4,2026-08-17,3.0,MUM,MH01,bean bags,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,10.0,10.0,0.000000,10.0,10.0,10.0,2026-08-17 14:26:31

In [12]:
# stress_level / combined / key
num = pd.to_numeric(df_sto_filtered['closing_inventory'], errors='coerce')
den = pd.to_numeric(df_sto_filtered['design_holding_capacity'], errors='coerce')
df_sto_filtered['stress_level'] = (num / den).replace([np.inf, -np.inf], np.nan)

# date as YYYY-MM-DD, falling back to the raw sheet value if it will not parse
_dt = pd.to_datetime(df_sto_filtered['date'], errors='coerce').dt.strftime('%Y-%m-%d')
date_str = _dt.astype('string').fillna(df_sto_filtered['date'].astype('string').str.strip())

wh = df_sto_filtered['warehouse_code'].astype('string').str.strip()
cat = df_sto_filtered['scm_product_category'].astype('string').str.strip()

df_sto_filtered['combined'] = date_str + '_' + wh + '_' + cat   # 2026-08-15_MUM_furniture
df_sto_filtered['key'] = wh + '-' + cat                          # MUM-furniture

no_cap = den.isna() | (den == 0)
print('rows:', len(df_sto_filtered),
      '| stress_level computed:', int(df_sto_filtered['stress_level'].notna().sum()),
      '| zero/blank design_holding_capacity:', int(no_cap.sum()),
      '| stock with no holding capacity (stress undefined):', int((no_cap & (num > 0)).sum()))
print('combined unique:', df_sto_filtered['combined'].nunique(), '| key unique:', df_sto_filtered['key'].nunique())
df_sto_filtered[['date', 'warehouse_code', 'scm_product_category', 'closing_inventory',
                 'design_holding_capacity', 'stress_level', 'combined', 'key']].head(5)

rows: 21120 | stress_level computed: 18161 | zero/blank design_holding_capacity: 2959 | stock with no holding capacity (stress undefined): 96
combined unique: 21120 | key unique: 352

,date,warehouse_code,scm_product_category,closing_inventory,design_holding_capacity,stress_level,combined,key
0,2026-08-17,MUM,furniture,1212.300000,783.0,1.548276,2026-08-17_MUM_furniture,MUM-furniture
1,2026-08-17,MUM,sofa,202.000000,135.0,1.496296,2026-08-17_MUM_sofa,MUM-sofa
2,2026-08-17,MUM,office chair,146.671667,299.0,0.490541,2026-08-17_MUM_office chair,MUM-office chair
3,2026-08-17,MUM,mattress,875.728176,1974.0,0.443631,2026-08-17_MUM_mattress,MUM-mattress
4,2026-08-17,MUM,bean bags,0.000000,10.0,0.000000,2026-08-17_MUM_bean bags,MUM-bean bags

In [13]:
df_sto_filtered.head()

,date,warehouse_id,warehouse_code,plant_code,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm,stress_level,combined,key
0,2026-08-17,3.0,MUM,MH01,furniture,284.0,57.880000,144.700000,428.700000,1641.0,659.0,1.0,711.0,783.0,1212.300000,0.0,0.0,0.0,2026-08-17 14:26:31,1.548276,2026-08-17_MUM_furniture,MUM-furniture
1,2026-08-17,3.0,MUM,MH01,sofa,120.0,8.952381,24.000000,144.000000,346.0,87.0,1.0,62.0,135.0,202.000000,0.0,0.0,0.0,2026-08-17 14:26:31,1.496296,2026-08-17_MUM_sofa,MUM-sofa
2,2026-08-17,3.0,MUM,MH01,office chair,87.0,30.328333,30.328333,117.328333,146.0,195.0,1.0,118.0,299.0,146.671667,153.0,153.0,118.0,2026-08-17 14:26:31,0.490541,2026-08-17_MUM_office chair,MUM-office chair
3,2026-08-17,3.0,MUM,MH01,mattress,186.0,83.271824,83.271824,269.271824,650.0,914.0,1.0,495.0,1974.0,875.728176,1324.0,1324.0,495.0,2026-08-17 14:26:31,0.443631,2026-08-17_MUM_mattress,MUM-mattress
4,2026-08-17,3.0,MUM,MH01,bean bags,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,10.0,10.0,0.000000,10.0,10.0,10.0,2026-08-17 14:26:31,0.000000,2026-08-17_MUM_bean bags,MUM-bean bags

In [14]:
# https://docs.google.com/spreadsheets/d/1sAURSGD1-eptSOWWZluWLIQa6S93Ni_zchpDvuY3lcI/edit?gid=1724026445#gid=1724026445
sheet_key = '1sAURSGD1-eptSOWWZluWLIQa6S93Ni_zchpDvuY3lcI'
tab_name = 'new_sto_alert'
clean_sheet(sheet_key, tab_name, range_string="A:AAZ")
write_sheet(sheet_key, tab_name, df_sto_filtered)

 Sheet cleared: new_sto_alert!A:AAZ
 Written to sheet: new_sto_alert