In [1]:
import snowflake.connector
print(snowflake.connector.__version__)

3.18.0

In [2]:
import sys
import os
import datetime as dt
from datetime import datetime, timedelta, date
import gspread
import gspread_dataframe
from gspread_dataframe import get_as_dataframe, set_with_dataframe
import pandas as pd
import sql_explorer as exp
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import json
import pytz
import warnings
warnings.filterwarnings('ignore')
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
import pandas as pd
import snowflake.connector
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

# Key defined at top level - NO indentation inside the triple quotes
PRIVATE_KEY_PEM = b"""\
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYbXBQvBKJc4/A
H+DcDYxwJHblV/9Kw3NtEt3LcpDrnz6Vd9cgIRveorcf/r9Y7CF5UnTrOLaC8wLz
W0wxbE/OK+KGI51DCft96AzQx50eWY6vyZAvnzCkz0D3XEUBdTi19m0JYolBbqKF
o+T7Kx49dBftpW9PCy+QmmLUXMWyZQKheH2gpgG8HZMKyzyjeWJaEwJ+0Y1TjJzx
Mu7BotGYgG4z4PU6ImGsPUUBEgaMM40gImqoaK6k25G0+nSyZppOWiMjVuj7LUFJ
vmKb5/gpIrkXq7IPbwRT7FVKG7OjLiDb53NldZQx67TqnSq/dpyAUGzWbqcHOaxn
tGEIPTKjAgMBAAECggEAFHvIdyD/ALel3rSp/AhaEgvkameL6Bkh3suFQLzRmshY
ma90Gl44p4+IOmV6g1GgIfShv6ZsaGaNw/RF5fJfOx6Mn2gTzxl9UWsopbnddGGm
mhrlJHEpEUzEtzkQEOUWzOUju/og5ckfUAQ5VkNyGeILASWVMrMXHkCQ/WbGLnXN
b24B0XGt3DBMwV2YQvOQooCTzQo3WPloQMWqYiP+4kHpGEs9w1lmMM2KgI+2m+UH
KYHkSj/5iCGQodRzdo16PvWRhzBUYHM7BnLN37n7uCRkr1d80Bot+9saZkOxIdUh
2jcuECYCky3cxjFYLyMT/6xKGxCPs2Mjh7egjBC32QKBgQDHjdNiF46Zu1/t6ytA
dGphWI390cCXyWxIHHEV2W/sG820zjbDKuHWFMAkql6ar/HLRpRANbx+bgen/4PL
3HAxmwXmEEjgXkt+g4za7xhrlzHHeFXFrAfpHaB//I7/u7qFozgfR/SWaZYiYJD2
8fUsGG9zHLaOERcMsxMlgv8YDwKBgQDDixJWTCahAjf2wW9lA/TEiwEKrNVM/73f
RpbLGv+P4Adb/xMoXOMxY3cZtU9sVjxgxuRqc3qTctIljEWkiJ1oxmclxOVLEXSC
oYPPv2sT72QOqzgnSqMg92uJ62KSbo0MwAYHmWrv2oSa/xI1W8F4soQ6A1uF/wjf
R/DXa4KILQKBgGH89YBkWuSISsm0Qa/LunUEm+y3859VC/O465q0A65n1LHk1KUv
SGfsFpGqivvgS5XqmV+SQ3W9p8rJwDj5jKn/Gn1nH7H0+5MrG55h65bhTlNJdqyz
FctVfft60+klkKiQhj1uAt9dB5jn3Cc2lpJJiWh3//hw0eWthUhVM9fnAoGAT5fo
GuBcSOVSSkpqQT/e/bFm9yVqnTDr5FojPwD6TWHvHO8yqRdGEvBdpkU60uo3IV1T
1FC08BeomkgCgPpquB8qFSGUA35TYmjD8mgD+dVTcPUYokWrKNwNFdKOCPSezTXM
PoOgF4lmuIBitP1oPuzLDaIYOu6YeeoailTkiPECgYEAuu0CErL5pz6gxRnS6UYw
HeE1+PgyThKPgWmdU1AIgp5GTqJ/dSjOpAfX/NHdeD/xnfhdLTFen9jamIqYP3a0
2eIcrxDpdXTKXtA8+WxA+Z/n/6DvMyzVtUhE5sjIEf4oN2ZM+VGg5y8VhHZZDS8p
XHoc8HDOddl1y2fq78vM66Q=
-----END PRIVATE KEY-----"""

private_key = serialization.load_pem_private_key(
    PRIVATE_KEY_PEM,
    password=None,
    backend=default_backend()
)

private_key_bytes = private_key.private_bytes(
    encoding=serialization.Encoding.DER,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption()
)

In [4]:
def query_execute(query):
    """
    Executes the given SQL query. Tries first with SCM schema, falls back to PUBLIC if SCM fails.
    """
    def run_query(schema):
        conn = snowflake.connector.connect(
            user='SHUVENDU_PRITAM',
            account='yf90836.ap-south-1.aws',
            private_key=private_key_bytes,
            warehouse='COMPUTE_WH',
            database='WAKEFIT_DB',
            schema=schema
        )
        cursor = conn.cursor()
        try:
            cursor.execute(query)
            data = cursor.fetchall()
            df = pd.DataFrame(data, columns=[desc[0].lower() for desc in cursor.description])
            print(f"Query executed in schema: {schema}")
            return df
        finally:
            cursor.close()
            conn.close()

    # Try SCM schema first
    try:
        return run_query('SCM')
    except Exception as e:
        print(f"Failed in SCM: {e}")
        print("Trying in PUBLIC schema...")
        try:
            return run_query('PUBLIC')
        except Exception as e:
            print(f"Failed in PUBLIC: {e}")
            print("Trying in CRM schema...")
            return run_query('CRM')

    
playground_id = 'shuvendu.pritam@wakefit.co'
playground_password = 'qkkefrQs3c'

In [5]:
credentials = {
  "type": "service_account",
  "project_id": "pexanalytics",
  "private_key_id": "c1f0f45e3821f94efb0b8998d3b07d8b43636af3",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsS7ncddhr5jKa\nK0X9CNB0Wbvy5nmOta1wffRtDI1U3vY8TnMo3bk66IlvL22MDesDJ7+v8s3e3zP6\npxpPcAEZiGEgwPBQGWRmaCDfGG8Q4uFM2TSjMRyDWqKab3I1rmgXjRhezt1PjuNf\nQFbR6VkBz5GRkmAdntMwl/7ucIZ6yqt24pIpidMyOI4Kdz07Y+LxJyq8rzMEEjcy\nfAQSxXL8D09qcb8BdfoQJYzF2kr16ssH1pXg21QJahFfJBMQ1Xz+OdcO+GPupWKu\nYBg6ltA67oPf3vjcUXjv2ippnSa7kzmdOOdow77PHjfdMKG52PyonQRTIsTC+Gl5\nxMa807W1AgMBAAECggEAHxASBLisWZupgNkPZ7S4nFl3RK4fuUZw7AiRUj3Cl0wR\nWcMNCQ+cbw3whT6oQeladvmqGgcs7aMRJH4PBMZdNGS9miGe0doaG0pnrsEheQpm\ncyvvzQI0MUxcZ3pzPVFhy+kwvRsPlGHfBVO8s2CeHvD0vimFMaHqUmb827Em1ak7\nrQkKlIiQ4S2EFQ8Cndhf5mBAEiksHxyCZaeNmPA8rdxf5mQcMhfURLSfpR86Zk90\nud53bm3AjI3GIX7D64XpyeEaEoExQpygXbiglFkJL+1FGdXlzvQuKAdIW14mg2ZF\notVfswZT7B8GB1vqsXkt+L1iNGzP0Cxpjk9xIpWg4QKBgQDWWqHB7Zj1eMkibm0U\nNhdnH1T4I888gX4OYDD8TEWfEnCHzkEhqyza8Pp/2ARHfYAQmSwLeuZ+yXoE+TjT\nGEbFztCyWQv223omQtbDTvvdcxQ+u+dFOVXeZpv8uzFiZb30Thr/+L0MUUgBb8v0\nEgk0mB/ZVfwlQ/GSwxI/NAJwZQKBgQDNxTxpoYrlEyiFpqd8xof/ASt8e1EItu7S\nkxfWgYym2uWO8lMd1h3/W6Q+vCLJxZMEJ/xsJ3difJuLldCc4ZsBKLJNHcPfHtl9\nLG7cEL0zx+WZ3WkqcqfydD0TcKOPhbAnw7m3uCzELu2//Xy6GvMviMjDbWeH028w\ns1FFF/vTEQKBgQDMh1wTE6fAiYi5fs4728UG06Gax2hlHlXuV6BGDGzd9JVFL+t7\nub4qBoeu1qp2oGxC6jRZm+I1Ff+EoVy0J1TYR5dgpZDB8feibGJJp6KxUa3+kgKB\nTcz+UcADLYZYkiXm52Ph3DBegWwIWukrsM3xzjmNgfr+f88QL2vIvNKa9QKBgCAa\nosdURehhqdPYYY9NJlC57P/5+XWjnPVLr89u3PP3eRNpaWBhVMLPmHuVPNRAOCTQ\n3Eg/jBfYmygXEro3VMjEgbUYbMP1+zbVZOJ+1hYrHP55lfvicaOZUSIkU9CDqi06\nE1K/sHRXYg6vTPN4WvLSo4giHKILcfCmOYrPKCIRAoGATY9SdhT1pBaEhY3dzdrM\n0zMj6e9Oj+GZjPwh5TIrNRTepcwIT5HWPZzoCc6jTIuPWYMsmHa/OtRZeif1oEbj\nba/lyd0P+RPH9dqbIbCQ4YWKO3xq+yqd4z4rPq+nCC0W3Q8axESOEk209GGk7Yu3\njl0pC0PKVaBWtXYREsY1b48=\n-----END PRIVATE KEY-----\n",
  "client_email": "pex-analytics@pexanalytics.iam.gserviceaccount.com",
  "client_id": "115540536484257911435",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/pex-analytics%40pexanalytics.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
gc=gspread.service_account_from_dict(credentials)

In [6]:
def read_sheet(sheet_key, tab_name):
    gc = gspread.service_account_from_dict(credentials)
    master = gc.open_by_key(sheet_key)
    wks_in = master.worksheet(tab_name)
    df = get_as_dataframe(wks_in, evaluate_formulas=True, skiprows=0)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    return df

def write_sheet(sheet_key, tab_name, df):
    gc = gspread.service_account_from_dict(credentials)
    master = gc.open_by_key(sheet_key)
    wks_out = master.worksheet(tab_name)
    set_with_dataframe(wks_out, df)
    print(' Written to sheet:', tab_name)

def clean_sheet(sheet_key, tab_name, range_string="A:AAZ"):
    gc = gspread.service_account_from_dict(credentials)
    master = gc.open_by_key(sheet_key)
    full_range = f"{tab_name}!{range_string}"
    master.values_clear(full_range)
    print(' Sheet cleared:', full_range)

def read_sheet_skip_row_1(sheet_key, tab_name):
    gc = gspread.service_account_from_dict(credentials)
    master = gc.open_by_key(sheet_key)
    wks_in = master.worksheet(tab_name)
    df = get_as_dataframe(wks_in, evaluate_formulas=True, skiprows=1)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    return df

In [7]:
# https://docs.google.com/spreadsheets/d/1LiCjKQ_7pSLM_4Db4ALSAClRmy0-WoU1Wl_lksZJaF8/edit?gid=0#gid=0
sheet_key = '1LiCjKQ_7pSLM_4Db4ALSAClRmy0-WoU1Wl_lksZJaF8'
tab_name = 'output'

In [8]:
df_sto = read_sheet(sheet_key, tab_name)
df_sto.head(5)

,date,warehouse_id,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm,shift_id
0,2026-10-21,45.0,sofa,0.0,10.0,27.0,10.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57,0.0
1,2026-10-21,45.0,furniture,0.0,18.0,45.0,18.000000,0.0,0.0,0.0,10.0,37.0,0.0,37.0,37.0,10.0,2026-10-21 02:35:57,0.0
2,2026-10-21,45.0,office chair,0.0,20.0,20.0,20.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57,0.0
3,2026-10-21,45.0,mattress,0.0,34.0,34.0,6403.442828,346.0,0.0,0.0,10.0,270.0,0.0,0.0,0.0,0.0,2026-10-21 02:35:57,0.0
4,2026-10-21,45.0,accessory,0.0,20.0,20.0,20.000000,492.0,0.0,0.0,10.0,0.0,472.0,0.0,0.0,0.0,2026-10-21 02:35:57,0.0

In [9]:
df_sto.columns

Index(['date', 'warehouse_id', 'scm_product_category', 'dispatch_capacity',
       'dispatch_capacity_lm', 'dispatch_capacity_lm_box_lvl',
       'expected_dispatch', 'opening_inventory', 'expected_arrival',
       'is_actual_load', 'design_unload_capacity', 'design_holding_capacity',
       'closing_inventory', 'space_available', 'calc_unloading_capacity',
       'unload_capacity', 'load_dttm', 'shift_id'],
      dtype='object')

In [10]:
df_sto=df_sto[['date','warehouse_id','scm_product_category','dispatch_capacity','dispatch_capacity_lm','dispatch_capacity_lm_box_lvl','expected_dispatch','opening_inventory','expected_arrival','is_actual_load','design_unload_capacity','design_holding_capacity','closing_inventory','space_available','calc_unloading_capacity','unload_capacity','load_dttm']]

In [11]:
master_warehouse = '''
select id, warehouse_code, plant_code from wakefit_db.crm.wf_master_warehouse
'''
df_master_warehouse = query_execute(master_warehouse)

Query executed in schema: SCM

In [12]:
# map warehouse_code / plant_code into df_sto  :  df_sto.warehouse_id -> df_master_warehouse.id
wh_map = df_master_warehouse.copy()
wh_map['id'] = pd.to_numeric(wh_map['id'], errors='coerce')
wh_map = wh_map.dropna(subset=['id']).drop_duplicates(subset=['id']).set_index('id')

df_sto['warehouse_id'] = pd.to_numeric(df_sto['warehouse_id'], errors='coerce')
df_sto['warehouse_code'] = df_sto['warehouse_id'].map(wh_map['warehouse_code'])
df_sto['plant_code'] = df_sto['warehouse_id'].map(wh_map['plant_code'])

# keep the two new columns beside warehouse_id
cols = list(df_sto.columns)
for c in ['plant_code', 'warehouse_code']:
    cols.insert(cols.index('warehouse_id') + 1, cols.pop(cols.index(c)))
df_sto = df_sto[cols]

unmapped = sorted(df_sto.loc[df_sto['warehouse_code'].isna(), 'warehouse_id'].dropna().unique())
print('rows:', len(df_sto),
      '| mapped:', int(df_sto['warehouse_code'].notna().sum()),
      '| unmapped warehouse_ids:', unmapped)
df_sto.head(5)

rows: 47040 | mapped: 47040 | unmapped warehouse_ids: []

,date,warehouse_id,warehouse_code,plant_code,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm
0,2026-10-21,45.0,HSR,TN03,sofa,0.0,10.0,27.0,10.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57
1,2026-10-21,45.0,HSR,TN03,furniture,0.0,18.0,45.0,18.000000,0.0,0.0,0.0,10.0,37.0,0.0,37.0,37.0,10.0,2026-10-21 02:35:57
2,2026-10-21,45.0,HSR,TN03,office chair,0.0,20.0,20.0,20.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57
3,2026-10-21,45.0,HSR,TN03,mattress,0.0,34.0,34.0,6403.442828,346.0,0.0,0.0,10.0,270.0,0.0,0.0,0.0,0.0,2026-10-21 02:35:57
4,2026-10-21,45.0,HSR,TN03,accessory,0.0,20.0,20.0,20.000000,492.0,0.0,0.0,10.0,0.0,472.0,0.0,0.0,0.0,2026-10-21 02:35:57

In [13]:
sheet_key = '1sAURSGD1-eptSOWWZluWLIQa6S93Ni_zchpDvuY3lcI'
tab_name = 'input_config'
input_config = read_sheet(sheet_key, tab_name)
input_config.head(5)

,warehouse_code,warehouse_code_all,no_of_days_demand,no_of_days_allocation,no_of_days_allocation_wise_speed,sto_run_time
0,AMD2,AMD2,60.0,60.0,60.0,4.0
1,BBR,BBR,NaN,NaN,NaN,5.0
2,BLR10,BLR10,NaN,NaN,NaN,6.0
3,BLR12,BLR12,NaN,NaN,NaN,NaN
4,BLR15,BLR15,NaN,NaN,NaN,NaN

In [14]:
# df_sto_filtered : keep only the warehouses listed in input_config.warehouse_code
def norm_code(s):
    return s.astype('string').str.strip().str.upper()

# config codes -> drop the blank / NaN rows that come from reading the whole sheet grid
cfg_key = norm_code(input_config['warehouse_code']).dropna()
cfg_key = cfg_key[cfg_key != '']
cfg_set = set(cfg_key)

sto_key = norm_code(df_sto['warehouse_code'])
df_sto_filtered = df_sto[sto_key.isin(cfg_set).fillna(False)].copy().reset_index(drop=True)

# reconciliation
sto_set = set(sto_key.dropna())
missing_in_sto = sorted(cfg_set - sto_set)
dropped_codes = sorted(sto_set - cfg_set)

print('config warehouses:', len(cfg_set))
print('df_sto rows:', len(df_sto), '-> df_sto_filtered rows:', len(df_sto_filtered))
print('warehouses kept:', df_sto_filtered['warehouse_code'].nunique())
print('in config but NOT in df_sto :', missing_in_sto)
print('in df_sto but NOT in config (dropped):', dropped_codes)
df_sto_filtered.head(5)

config warehouses: 48
df_sto rows: 47040 -> df_sto_filtered rows: 22560
warehouses kept: 47
in config but NOT in df_sto : ['MAN_RETAIL_1']
in df_sto but NOT in config (dropped): ['AMD', 'ANT', 'BLR', 'BLR1', 'BLR11', 'BLR13', 'BLR2', 'BLR3', 'BLR4', 'BLR5', 'BLR6', 'BLR9', 'BPL', 'CHN', 'CHN1', 'DEL', 'DWK', 'FBD2', 'GRG', 'GRG1', 'GRG2', 'GRG3', 'GRG4', 'HSR10', 'HSR11', 'HSR12', 'HSR13', 'HSR15', 'HSR3', 'HSR4', 'HSR7', 'HSR8', 'HSR9', 'HYD', 'HYD1', 'HYD2', 'HYD_2', 'JDH', 'JDH1', 'JDH2', 'JPR', 'KOL', 'LUK1', 'MBD', 'OKL', 'PUN', 'PUN1', 'PUN2', 'RJA', 'RNC', 'TRV']

,date,warehouse_id,warehouse_code,plant_code,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm
0,2026-10-21,45.0,HSR,TN03,sofa,0.0,10.0,27.0,10.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57
1,2026-10-21,45.0,HSR,TN03,furniture,0.0,18.0,45.0,18.000000,0.0,0.0,0.0,10.0,37.0,0.0,37.0,37.0,10.0,2026-10-21 02:35:57
2,2026-10-21,45.0,HSR,TN03,office chair,0.0,20.0,20.0,20.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57
3,2026-10-21,45.0,HSR,TN03,mattress,0.0,34.0,34.0,6403.442828,346.0,0.0,0.0,10.0,270.0,0.0,0.0,0.0,0.0,2026-10-21 02:35:57
4,2026-10-21,45.0,HSR,TN03,accessory,0.0,20.0,20.0,20.000000,492.0,0.0,0.0,10.0,0.0,472.0,0.0,0.0,0.0,2026-10-21 02:35:57

In [15]:
# stress_level / combined / key
num = pd.to_numeric(df_sto_filtered['closing_inventory'], errors='coerce')
den = pd.to_numeric(df_sto_filtered['design_holding_capacity'], errors='coerce')
df_sto_filtered['stress_level'] = (num / den).replace([np.inf, -np.inf], np.nan)

# date as YYYY-MM-DD, falling back to the raw sheet value if it will not parse
_dt = pd.to_datetime(df_sto_filtered['date'], errors='coerce').dt.strftime('%Y-%m-%d')
date_str = _dt.astype('string').fillna(df_sto_filtered['date'].astype('string').str.strip())

wh = df_sto_filtered['warehouse_code'].astype('string').str.strip()
cat = df_sto_filtered['scm_product_category'].astype('string').str.strip()

df_sto_filtered['combined'] = date_str + '_' + wh + '_' + cat   # 2026-08-15_MUM_furniture
df_sto_filtered['key'] = wh + '-' + cat                          # MUM-furniture

no_cap = den.isna() | (den == 0)
print('rows:', len(df_sto_filtered),
      '| stress_level computed:', int(df_sto_filtered['stress_level'].notna().sum()),
      '| zero/blank design_holding_capacity:', int(no_cap.sum()),
      '| stock with no holding capacity (stress undefined):', int((no_cap & (num > 0)).sum()))
print('combined unique:', df_sto_filtered['combined'].nunique(), '| key unique:', df_sto_filtered['key'].nunique())
df_sto_filtered[['date', 'warehouse_code', 'scm_product_category', 'closing_inventory',
                 'design_holding_capacity', 'stress_level', 'combined', 'key']].head(5)

rows: 22560 | stress_level computed: 16410 | zero/blank design_holding_capacity: 6150 | stock with no holding capacity (stress undefined): 72
combined unique: 22560 | key unique: 376

,date,warehouse_code,scm_product_category,closing_inventory,design_holding_capacity,stress_level,combined,key
0,2026-10-21,HSR,sofa,0.0,15.0,0.0,2026-10-21_HSR_sofa,HSR-sofa
1,2026-10-21,HSR,furniture,0.0,37.0,0.0,2026-10-21_HSR_furniture,HSR-furniture
2,2026-10-21,HSR,office chair,0.0,15.0,0.0,2026-10-21_HSR_office chair,HSR-office chair
3,2026-10-21,HSR,mattress,0.0,270.0,0.0,2026-10-21_HSR_mattress,HSR-mattress
4,2026-10-21,HSR,accessory,472.0,0.0,NaN,2026-10-21_HSR_accessory,HSR-accessory

In [16]:
df_sto_filtered.head()

,date,warehouse_id,warehouse_code,plant_code,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm,stress_level,combined,key
0,2026-10-21,45.0,HSR,TN03,sofa,0.0,10.0,27.0,10.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57,0.0,2026-10-21_HSR_sofa,HSR-sofa
1,2026-10-21,45.0,HSR,TN03,furniture,0.0,18.0,45.0,18.000000,0.0,0.0,0.0,10.0,37.0,0.0,37.0,37.0,10.0,2026-10-21 02:35:57,0.0,2026-10-21_HSR_furniture,HSR-furniture
2,2026-10-21,45.0,HSR,TN03,office chair,0.0,20.0,20.0,20.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57,0.0,2026-10-21_HSR_office chair,HSR-office chair
3,2026-10-21,45.0,HSR,TN03,mattress,0.0,34.0,34.0,6403.442828,346.0,0.0,0.0,10.0,270.0,0.0,0.0,0.0,0.0,2026-10-21 02:35:57,0.0,2026-10-21_HSR_mattress,HSR-mattress
4,2026-10-21,45.0,HSR,TN03,accessory,0.0,20.0,20.0,20.000000,492.0,0.0,0.0,10.0,0.0,472.0,0.0,0.0,0.0,2026-10-21 02:35:57,NaN,2026-10-21_HSR_accessory,HSR-accessory

In [17]:
# https://docs.google.com/spreadsheets/d/1sAURSGD1-eptSOWWZluWLIQa6S93Ni_zchpDvuY3lcI/edit?gid=1724026445#gid=1724026445
sheet_key = '1sAURSGD1-eptSOWWZluWLIQa6S93Ni_zchpDvuY3lcI'
tab_name = 'new_sto_alert'
clean_sheet(sheet_key, tab_name, range_string="A:AAZ")
write_sheet(sheet_key, tab_name, df_sto_filtered)

 Sheet cleared: new_sto_alert!A:AAZ
 Written to sheet: new_sto_alert

In [18]:
# https://docs.google.com/spreadsheets/d/1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8/edit?gid=1065998849#gid=1065998849
sheet_key = '1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8'
tab_name = 'sto_alert'
clean_sheet(sheet_key, tab_name, range_string="A:AAZ")
write_sheet(sheet_key, tab_name, df_sto_filtered)

 Sheet cleared: sto_alert!A:AAZ
 Written to sheet: sto_alert

In [19]:
# latest-date slice : keep only the earliest date in the frame (= today's snapshot row)
latest_date = min(df_sto_filtered['date'])
df_sto_filtered_latest_date = df_sto_filtered[df_sto_filtered['date'] == latest_date].copy().reset_index(drop=True)

print('latest_date:', latest_date,
      '| rows:', len(df_sto_filtered_latest_date),
      '| warehouses:', df_sto_filtered_latest_date['warehouse_code'].nunique(),
      '| keys:', df_sto_filtered_latest_date['key'].nunique())
df_sto_filtered_latest_date.head(5)

latest_date: 2026-10-21 | rows: 376 | warehouses: 47 | keys: 376

,date,warehouse_id,warehouse_code,plant_code,scm_product_category,dispatch_capacity,dispatch_capacity_lm,dispatch_capacity_lm_box_lvl,expected_dispatch,opening_inventory,expected_arrival,is_actual_load,design_unload_capacity,design_holding_capacity,closing_inventory,space_available,calc_unloading_capacity,unload_capacity,load_dttm,stress_level,combined,key
0,2026-10-21,45.0,HSR,TN03,sofa,0.0,10.0,27.0,10.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57,0.0,2026-10-21_HSR_sofa,HSR-sofa
1,2026-10-21,45.0,HSR,TN03,furniture,0.0,18.0,45.0,18.000000,0.0,0.0,0.0,10.0,37.0,0.0,37.0,37.0,10.0,2026-10-21 02:35:57,0.0,2026-10-21_HSR_furniture,HSR-furniture
2,2026-10-21,45.0,HSR,TN03,office chair,0.0,20.0,20.0,20.000000,0.0,0.0,0.0,10.0,15.0,0.0,15.0,15.0,10.0,2026-10-21 02:35:57,0.0,2026-10-21_HSR_office chair,HSR-office chair
3,2026-10-21,45.0,HSR,TN03,mattress,0.0,34.0,34.0,6403.442828,346.0,0.0,0.0,10.0,270.0,0.0,0.0,0.0,0.0,2026-10-21 02:35:57,0.0,2026-10-21_HSR_mattress,HSR-mattress
4,2026-10-21,45.0,HSR,TN03,accessory,0.0,20.0,20.0,20.000000,492.0,0.0,0.0,10.0,0.0,472.0,0.0,0.0,0.0,2026-10-21 02:35:57,NaN,2026-10-21_HSR_accessory,HSR-accessory

In [20]:
# https://docs.google.com/spreadsheets/d/1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8/edit?gid=1065998849#gid=1065998849
sheet_key = '1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8'
tab_name = 'recent_sto_alert_data'
clean_sheet(sheet_key, tab_name, range_string="A:AAZ")
write_sheet(sheet_key, tab_name, df_sto_filtered_latest_date)

 Sheet cleared: recent_sto_alert_data!A:AAZ
 Written to sheet: recent_sto_alert_data

In [21]:
# measure grid : every unique warehouse-category key x data_measure x type
# NOTE: spellings below are verbatim from the spec - edit these two lists in one place if they change.
DATA_MEASURES = [
    'lm_local_capacity',
    'lm_3pl_capacity',
    'total_lm_capacity',
    'mm_dispatch_capacity',
    'unloading_capacity',
    'holding_capacity',
]

TYPES = [
    'data_team',
    'planning',
    'pex',
    'ceiling',
]

base = (df_sto_filtered_latest_date[['key', 'warehouse_code', 'scm_product_category']]
        .drop_duplicates(subset='key')
        .rename(columns={'warehouse_code': 'warehouse',
                         'scm_product_category': 'scm_master_category'})
        .reset_index(drop=True))

df_measure_grid = (base
                   .merge(pd.DataFrame({'data_measure': DATA_MEASURES}), how='cross')
                   .merge(pd.DataFrame({'type': TYPES}), how='cross'))

print('keys:', len(base),
      '| measures:', len(DATA_MEASURES),
      '| types:', len(TYPES),
      '| rows:', len(df_measure_grid),
      '| expected:', len(base) * len(DATA_MEASURES) * len(TYPES),
      '| duplicate key+measure+type:', int(df_measure_grid.duplicated(subset=['key', 'data_measure', 'type']).sum()))
df_measure_grid.head(24)

keys: 376 | measures: 6 | types: 4 | rows: 9024 | expected: 9024 | duplicate key+measure+type: 0

         key warehouse scm_master_category          data_measure       type
0   HSR-sofa       HSR                sofa     lm_local_capacity  data_team
1   HSR-sofa       HSR                sofa     lm_local_capacity   planning
2   HSR-sofa       HSR                sofa     lm_local_capacity        pex
3   HSR-sofa       HSR                sofa     lm_local_capacity    ceiling
4   HSR-sofa       HSR                sofa       lm_3pl_capacity  data_team
5   HSR-sofa       HSR                sofa       lm_3pl_capacity   planning
6   HSR-sofa       HSR                sofa       lm_3pl_capacity        pex
7   HSR-sofa       HSR                sofa       lm_3pl_capacity    ceiling
8   HSR-sofa       HSR                sofa     total_lm_capacity  data_team
9   HSR-sofa       HSR                sofa     total_lm_capacity   planning
10  HSR-sofa       HSR                sofa     total_lm_capacity        pex
11  HSR-sofa       HSR                sofa     total_lm_capacity    ceiling
12  HSR-sofa       HSR                sofa  mm_dispatch_capacity  data_team
13  HSR-sofa       HSR                sofa  mm_dispatch_capacity   planning
14  HSR-sofa       HSR                sofa  mm_dispatch_capacity        pex
15  HSR-sofa       HSR                sofa  mm_dispatch_capacity    ceiling
16  HSR-sofa       HSR                sofa    unloading_capacity  data_team
17  HSR-sofa       HSR                sofa    unloading_capacity   planning
18  HSR-sofa       HSR                sofa    unloading_capacity        pex
19  HSR-sofa       HSR                sofa    unloading_capacity    ceiling
20  HSR-sofa       HSR                sofa      holding_capacity  data_team
21  HSR-sofa       HSR                sofa      holding_capacity   planning
22  HSR-sofa       HSR                sofa      holding_capacity        pex
23  HSR-sofa       HSR                sofa      holding_capacity    ceiling

In [22]:
df_measure_grid.shape

(9024, 5)

In [23]:
# https://docs.google.com/spreadsheets/d/1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8/edit?gid=1065998849#gid=1065998849
sheet_key = '1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8'
tab_name = 'input_measure_grid'
clean_sheet(sheet_key, tab_name, range_string="A:E")
write_sheet(sheet_key, tab_name, df_measure_grid)

 Sheet cleared: input_measure_grid!A:E
 Written to sheet: input_measure_grid

In [24]:
tt_tf = f"""
   WITH combined_transit AS (
    SELECT 
        mother_warehouse AS source_id, 
        inhp_warehouse AS dest_id, 
        sku_code, 
        transit_time, 
        transit_frequency 
    FROM wakefit_db.crm.wf_inhp_mother_mapping 
    WHERE mother_warehouse != inhp_warehouse

    UNION ALL

    SELECT 
        inhp_warehouse AS source_id, 
        pod_warehouse AS dest_id, 
        sku_code, 
        transit_time, 
        transit_frequency 
    FROM wakefit_db.crm.wf_pods_inhp_mapping 
    WHERE inhp_warehouse != pod_warehouse
)
SELECT 
    t.source_id,
    src_wh.warehouse_code AS source_warehouse_code,
    src_wh.plant_code AS source_plant_code,
    t.dest_id,
    dest_wh.warehouse_code AS dest_warehouse_code,
    dest_wh.plant_code AS dest_plant_code,
    t.sku_code,
    p.scm_master_category,
    t.transit_time,
    t.transit_frequency
FROM combined_transit t
LEFT JOIN (
    SELECT DISTINCT sku_code, scm_master_category 
    FROM wakefit_db.crm.wf_products_pricing
) p 
    ON t.sku_code = p.sku_code
LEFT JOIN (
    SELECT DISTINCT id, warehouse_code, plant_code 
    FROM wakefit_db.crm.wf_master_warehouse
) src_wh 
    ON t.source_id = src_wh.id
LEFT JOIN (
    SELECT DISTINCT id, warehouse_code, plant_code 
    FROM wakefit_db.crm.wf_master_warehouse
) dest_wh 
    ON t.dest_id = dest_wh.id; 
"""
tt_tf = query_execute(tt_tf)

Query executed in schema: SCM

In [25]:
tt_tf.head()

,source_id,source_warehouse_code,source_plant_code,dest_id,dest_warehouse_code,dest_plant_code,sku_code,scm_master_category,transit_time,transit_frequency
0,3,MUM,MH01,15,IDR,MP02,WDCM,mattress,1,3
1,3,MUM,MH01,15,IDR,MP02,WOMFM,mattress,1,3
2,3,MUM,MH01,15,IDR,MP02,WMFWLM,mattress,1,3
3,3,MUM,MH01,15,IDR,MP02,WPSFM,mattress,1,3
4,3,MUM,MH01,15,IDR,MP02,PFGM,mattress,1,3

In [26]:
# tt_tf_final : source x destination x scm_master_category -> modal transit_time / transit_frequency
#
#   transit_time / transit_frequency  = the MODE, i.e. an actual observed value (0, 1, 2, 3 ...).
#                                       Multi-modal -> take the LARGEST of the tied values.
#   *_agreement_pct                   = diagnostic only: % of skus in the group that carried
#                                       that modal value. 93.0 means 93% agreed, 7% differed.
#                                       This is NOT the transit time.

GRP = ['source_id', 'source_warehouse_code', 'source_plant_code',
       'dest_id', 'dest_warehouse_code', 'dest_plant_code', 'scm_master_category']

_tt = tt_tf.copy()
for c in ['transit_time', 'transit_frequency']:
    _tt[c] = pd.to_numeric(_tt[c], errors='coerce')

def _mode(s):
    """Most frequent value. Tied on frequency -> largest, so planning never under-states."""
    m = s.dropna().mode()
    return np.nan if m.empty else m.max()

def _n_modes(s):
    return len(s.dropna().mode())

def _agreement_pct(s):
    s = s.dropna()
    return np.nan if s.empty else round(s.value_counts(normalize=True).iloc[0] * 100, 1)

tt_tf_final = (_tt.groupby(GRP, dropna=False)
               .agg(transit_time=('transit_time', _mode),
                    transit_frequency=('transit_frequency', _mode),
                    sku_count=('sku_code', 'nunique'),
                    tt_distinct=('transit_time', 'nunique'),
                    tf_distinct=('transit_frequency', 'nunique'),
                    tt_agreement_pct=('transit_time', _agreement_pct),
                    tf_agreement_pct=('transit_frequency', _agreement_pct),
                    tt_n_modes=('transit_time', _n_modes),
                    tf_n_modes=('transit_frequency', _n_modes))
               .reset_index())

src = tt_tf_final['source_warehouse_code'].astype('string').str.strip()
dst = tt_tf_final['dest_warehouse_code'].astype('string').str.strip()
cat = tt_tf_final['scm_master_category'].astype('string').str.strip()
tt_tf_final['lane'] = src + '-' + dst                 # HSR-MUM
tt_tf_final['key'] = src + '-' + dst + '-' + cat      # HSR-MUM-mattress

# reconciliation
print('sku-level rows:', len(tt_tf), '-> tt_tf_final rows:', len(tt_tf_final))
print('lanes:', tt_tf_final['lane'].nunique(), '| categories:', cat.nunique(dropna=True))
print('duplicate source+dest+category:', int(tt_tf_final.duplicated(subset=['source_id', 'dest_id', 'scm_master_category']).sum()))
print('sku with no scm_master_category (rows):', int(tt_tf['scm_master_category'].isna().sum()),
      '| groups:', int(tt_tf_final['scm_master_category'].isna().sum()))
print('unmapped source_warehouse_code:', int(tt_tf_final['source_warehouse_code'].isna().sum()),
      '| unmapped dest_warehouse_code:', int(tt_tf_final['dest_warehouse_code'].isna().sum()))
print('mixed tt within group:', int((tt_tf_final['tt_distinct'] > 1).sum()),
      '| mixed tf within group:', int((tt_tf_final['tf_distinct'] > 1).sum()))
print('multi-modal groups, largest taken -> tt:', int((tt_tf_final['tt_n_modes'] > 1).sum()),
      '| tf:', int((tt_tf_final['tf_n_modes'] > 1).sum()))
print('tt values seen:', sorted(tt_tf_final['transit_time'].dropna().unique()))
print('tf values seen:', sorted(tt_tf_final['transit_frequency'].dropna().unique()))
print('tt_agreement_pct min/median:', tt_tf_final['tt_agreement_pct'].min(), '/', tt_tf_final['tt_agreement_pct'].median(),
      '| tf_agreement_pct min/median:', tt_tf_final['tf_agreement_pct'].min(), '/', tt_tf_final['tf_agreement_pct'].median())
print('tt null:', int(tt_tf_final['transit_time'].isna().sum()),
      '| tf null:', int(tt_tf_final['transit_frequency'].isna().sum()))

tt_tf_final = (tt_tf_final
               .drop(columns=['tt_n_modes', 'tf_n_modes'])
               .sort_values(['source_warehouse_code', 'dest_warehouse_code', 'scm_master_category'])
               .reset_index(drop=True))

tt_tf_final.head(10)

sku-level rows: 1359710 -> tt_tf_final rows: 494
lanes: 133 | categories: 10
duplicate source+dest+category: 0
sku with no scm_master_category (rows): 8 | groups: 2
unmapped source_warehouse_code: 0 | unmapped dest_warehouse_code: 0
mixed tt within group: 23 | mixed tf within group: 29
multi-modal groups, largest taken -> tt: 0 | tf: 0
tt values seen: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(15)]
tf values seen: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(15)]
tt_agreement_pct min/median: 66.7 / 100.0 | tf_agreement_pct min/median: 53.6 / 100.0
tt null: 0 | tf null: 0

,source_id,source_warehouse_code,source_plant_code,dest_id,dest_warehouse_code,dest_plant_code,scm_master_category,transit_time,transit_frequency,sku_count,tt_distinct,tf_distinct,tt_agreement_pct,tf_agreement_pct,lane,key
0,178,BLR10,KA13,242,AMD2,GJ03,accessory,15,15,35,1,1,100.0,100.0,BLR10-AMD2,BLR10-AMD2-accessory
1,178,BLR10,KA13,241,DWK2,DL04,accessory,15,15,35,1,1,100.0,100.0,BLR10-DWK2,BLR10-DWK2-accessory
2,178,BLR10,KA13,181,HYD3,TS02,accessory,15,15,35,1,1,100.0,100.0,BLR10-HYD3,BLR10-HYD3-accessory
3,178,BLR10,KA13,179,KOL2,WB03,accessory,15,15,35,1,1,100.0,100.0,BLR10-KOL2,BLR10-KOL2-accessory
4,178,BLR10,KA13,3,MUM,MH01,accessory,15,15,35,1,1,100.0,100.0,BLR10-MUM,BLR10-MUM-accessory
5,183,BLR12,MKA9,181,HYD3,TS02,accessory,2,1,1,1,1,100.0,100.0,BLR12-HYD3,BLR12-HYD3-accessory
6,195,BLR15,KA15,242,AMD2,GJ03,accessory,15,15,25,1,1,100.0,100.0,BLR15-AMD2,BLR15-AMD2-accessory
7,195,BLR15,KA15,242,AMD2,GJ03,mattress,15,15,1,1,1,100.0,100.0,BLR15-AMD2,BLR15-AMD2-mattress
8,195,BLR15,KA15,183,BLR12,MKA9,accessory,0,0,15,1,1,100.0,100.0,BLR15-BLR12,BLR15-BLR12-accessory
9,195,BLR15,KA15,183,BLR12,MKA9,bean bags,0,0,1,1,1,100.0,100.0,BLR15-BLR12,BLR15-BLR12-bean bags

In [27]:
# https://docs.google.com/spreadsheets/d/1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8/edit?gid=606887868#gid=606887868
clean_sheet('1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8','tt_tf')
write_sheet('1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8','tt_tf', tt_tf_final)

 Sheet cleared: tt_tf!A:AAZ
 Written to sheet: tt_tf

In [28]:
# https://docs.google.com/spreadsheets/d/1KcbJW7uBSsmD8on0pi1teysQAvlBu1zWMpHZX3TQmxk/edit?gid=129165972#gid=129165972
df_lm_capacity_local = read_sheet('1KcbJW7uBSsmD8on0pi1teysQAvlBu1zWMpHZX3TQmxk','BAU_Local')
df_lm_capacity_3pl = read_sheet('1KcbJW7uBSsmD8on0pi1teysQAvlBu1zWMpHZX3TQmxk','BAU_3PL')
df_mm_capacity = read_sheet('1KcbJW7uBSsmD8on0pi1teysQAvlBu1zWMpHZX3TQmxk','MM Capacity BAU - 1')

In [29]:
df_lm_capacity_local.head(5)

,warehouse,accessory,furniture,office chair,mattress,sofa,bean bags,zense,dealer_mts
0,AMD2,0,28,16,130,6,0,0,5
1,BBR,0,16,7,43,2,0,0,2
2,BLR10,0,0,0,0,0,0,0,0
3,BLR15,0,0,0,0,0,0,0,0
4,BLR16,0,0,0,150,0,0,0,2

In [30]:
df_lm_capacity_3pl.head(5)

,warehouse,accessory,furniture,office chair,mattress,sofa,bean bags,zense,dealer_mts
0,AMD2,250,0,0,0,0,0,0,0
1,BBR,0,0,0,0,0,0,0,0
2,BLR10,500,0,0,0,0,0,0,0
3,BLR15,4646,0,0,0,0,0,0,0
4,BLR16,0,0,0,0,0,0,0,0

In [31]:
df_mm_capacity.head(5)

,warehouse,accessory-unloading,furniture-unloading,office chair-unloading,mattress-unloading,sofa-unloading,bean bags-unloading,zense-unloading,dealer_mts-unloading,accessory-mm_dispatch,furniture-mm_dispatch,office chair-mm_dispatch,mattress-mm_dispatch,sofa-mm_dispatch,bean bags-mm_dispatch,zense-mm_dispatch,dealer_mts-mm_dispatch,accessory-holding,furniture-holding,office chair-holding,mattress-holding,sofa-holding,bean bags-holding,zense-holding,dealer_mts-holding,accessory-installation,furniture-installation,office chair-installation,mattress-installation,sofa-installation,bean bags-installation,zense-installation,dealer_mts-installation
0,AMD2,375,105,24,195,27,10,10,10,0,0,0,0,0,0,10,10,1295,161,44,357,51,65,10,16,0,26,0,0,6,0,0,0
1,BBR,10,60,11,65,10,10,10,10,0,0,0,0,0,0,10,10,0,132,33,94,15,0,10,10,0,15,0,0,5,0,0,0
2,BLR10,750,10,10,10,10,10,10,10,0,0,0,0,0,0,10,10,31500,37,24,50,15,1575,10,10,0,5,0,0,5,0,0,0
3,BLR15,6969,10,10,10,10,10,10,10,0,0,0,0,0,0,10,10,18000,37,15,50,15,900,10,10,0,5,0,0,5,0,0,0
4,BLR16,10,10,10,225,10,10,10,10,0,0,0,0,0,0,10,10,0,37,15,344,15,0,10,10,0,5,0,0,5,0,0,0

### planning capacity tables -> `1ej_Fbl2...`

Melt the wide BAU capacity sheets in `1KcbJW7u...` into long tables the measure grid can join to.

| tab | columns | example |
|---|---|---|
| `lm_planning_capacity` | `warehouse` `scm_master_category` `lp` `capacity` | `AMD2 furniture local 27` / `AMD2 furniture 3pl 0` |
| `mm_planning_capacity` | `warehouse` `scm_master_category` `data_measure` `value` | `AMD2 accessory unloading 10` / `AMD2 accessory mm_dispatch 0` / `AMD2 accessory holding 10` |

In [32]:
# lm_planning_capacity : BAU_Local + BAU_3PL (wide) -> long
#
#   warehouse | scm_master_category | lp    | capacity
#   AMD2        furniture             local    27
#   AMD2        furniture             3pl      0
#
# Built off a full warehouse x category x lp grid, so every combination carries BOTH lp rows.
# A 0 therefore means "no capacity with that partner", never "row missing from the sheet".

CATEGORY_COLS = ['accessory', 'furniture', 'office chair', 'mattress',
                 'sofa', 'bean bags', 'zense', 'dealer_mts']

def _melt_lm(df, lp):
    d = df.copy()
    d['warehouse'] = d['warehouse'].astype('string').str.strip()
    d = d[d['warehouse'].notna() & (d['warehouse'] != '')]        # drop the blank sheet-grid rows
    absent = [c for c in CATEGORY_COLS if c not in d.columns]
    if absent:
        print(f'  {lp}: category columns not in sheet ->', absent)
    out = d.melt(id_vars='warehouse',
                 value_vars=[c for c in CATEGORY_COLS if c in d.columns],
                 var_name='scm_master_category', value_name='capacity')
    out['capacity'] = pd.to_numeric(out['capacity'], errors='coerce')
    out['lp'] = lp
    return out[['warehouse', 'scm_master_category', 'lp', 'capacity']]

lm_melted = pd.concat([_melt_lm(df_lm_capacity_local, 'local'),
                       _melt_lm(df_lm_capacity_3pl, '3pl')], ignore_index=True)

lm_dupes = int(lm_melted.duplicated(subset=['warehouse', 'scm_master_category', 'lp']).sum())
lm_melted = lm_melted.drop_duplicates(subset=['warehouse', 'scm_master_category', 'lp'], keep='first')

lm_grid = (pd.DataFrame({'warehouse': sorted(set(lm_melted['warehouse']))})
           .merge(pd.DataFrame({'scm_master_category': CATEGORY_COLS}), how='cross')
           .merge(pd.DataFrame({'lp': ['local', '3pl']}), how='cross'))

df_lm_planning_capacity = lm_grid.merge(lm_melted, how='left',
                                        on=['warehouse', 'scm_master_category', 'lp'])
lm_blank = int(df_lm_planning_capacity['capacity'].isna().sum())
df_lm_planning_capacity['capacity'] = df_lm_planning_capacity['capacity'].fillna(0)

# reconciliation
wh_local = set(lm_melted.loc[lm_melted['lp'].eq('local'), 'warehouse'])
wh_3pl = set(lm_melted.loc[lm_melted['lp'].eq('3pl'), 'warehouse'])
wh_all = wh_local | wh_3pl

print('warehouses  BAU_Local:', len(wh_local), '| BAU_3PL:', len(wh_3pl), '| union:', len(wh_all))
print('in BAU_Local only:', sorted(wh_local - wh_3pl), '| in BAU_3PL only:', sorted(wh_3pl - wh_local))
print('rows:', len(df_lm_planning_capacity),
      '| expected:', len(wh_all) * len(CATEGORY_COLS) * 2,
      '| duplicate warehouse+category+lp in source:', lm_dupes,
      '| grid cells with no sheet value (0-filled):', lm_blank)
print('capacity total  local:', df_lm_planning_capacity.loc[df_lm_planning_capacity['lp'].eq('local'), 'capacity'].sum(),
      '| 3pl:', df_lm_planning_capacity.loc[df_lm_planning_capacity['lp'].eq('3pl'), 'capacity'].sum())

if 'df_sto_filtered_latest_date' in globals():
    sto_wh = set(df_sto_filtered_latest_date['warehouse_code'].astype('string').str.strip().dropna())
    print('in STO scope but no LM capacity :', sorted(sto_wh - wh_all))
    print('LM capacity but not in STO scope:', sorted(wh_all - sto_wh))

df_lm_planning_capacity.head(16)

warehouses  BAU_Local: 46 | BAU_3PL: 46 | union: 46
in BAU_Local only: [] | in BAU_3PL only: []
rows: 736 | expected: 736 | duplicate warehouse+category+lp in source: 0 | grid cells with no sheet value (0-filled): 0
capacity total  local: 7553 | 3pl: 24928
in STO scope but no LM capacity : ['FBD', 'PTN', 'SPT']
LM capacity but not in STO scope: ['HSR15', 'MAN_RETAIL_1']

   warehouse scm_master_category     lp  capacity
0       AMD2           accessory  local         0
1       AMD2           accessory    3pl       250
2       AMD2           furniture  local        28
3       AMD2           furniture    3pl         0
4       AMD2        office chair  local        16
5       AMD2        office chair    3pl         0
6       AMD2            mattress  local       130
7       AMD2            mattress    3pl         0
8       AMD2                sofa  local         6
9       AMD2                sofa    3pl         0
10      AMD2           bean bags  local         0
11      AMD2           bean bags    3pl         0
12      AMD2               zense  local         0
13      AMD2               zense    3pl         0
14      AMD2          dealer_mts  local         5
15      AMD2          dealer_mts    3pl         0

In [33]:
# https://docs.google.com/spreadsheets/d/1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8/edit?gid=1646483343#gid=1646483343
# A:D only - the script owns four columns, anything maintained to the right of them survives.
clean_sheet('1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8', 'lm_planning_capacity', range_string="A:D")
write_sheet('1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8', 'lm_planning_capacity', df_lm_planning_capacity)

 Sheet cleared: lm_planning_capacity!A:D
 Written to sheet: lm_planning_capacity

In [34]:
# mm_planning_capacity : 'MM Capacity BAU - 1' (wide, '<category>-<data_measure>') -> long
#
#   warehouse | scm_master_category | data_measure | value
#   AMD2        accessory             unloading      10
#   AMD2        accessory             mm_dispatch    0
#   AMD2        accessory             holding        10
#
# MM_MEASURES mirrors DATA_MEASURES in the measure grid, which carries no installation
# figure - so the sheet's '-installation' columns are read and then dropped. Add
# 'installation' to the list below if you want them in the table.

MM_MEASURES = ['unloading', 'mm_dispatch', 'holding']

_mm = df_mm_capacity.copy()
_mm['warehouse'] = _mm['warehouse'].astype('string').str.strip()
_mm = _mm[_mm['warehouse'].notna() & (_mm['warehouse'] != '')]

mm_melted = _mm.melt(id_vars='warehouse',
                     value_vars=[c for c in _mm.columns if c != 'warehouse'],
                     var_name='col', value_name='value')

# '<category>-<data_measure>' : split on the LAST hyphen. Safe both ways - no category
# contains a hyphen, and the measures use '_' (mm_dispatch, dealer_mts).
_split = (mm_melted['col'].astype('string').str.strip()
          .str.rsplit('-', n=1, expand=True).reindex(columns=[0, 1]))
mm_melted['scm_master_category'] = _split[0].str.strip()
mm_melted['data_measure'] = _split[1].str.strip()
mm_melted['value'] = pd.to_numeric(mm_melted['value'], errors='coerce')

unparsed = sorted(mm_melted.loc[mm_melted['data_measure'].isna(), 'col'].astype('string').unique())
off_cat = sorted(set(mm_melted['scm_master_category'].dropna()) - set(CATEGORY_COLS))
off_measure = sorted(set(mm_melted['data_measure'].dropna()) - set(MM_MEASURES))

mm_dupes = int(mm_melted.duplicated(subset=['warehouse', 'scm_master_category', 'data_measure']).sum())
mm_melted = mm_melted.drop_duplicates(subset=['warehouse', 'scm_master_category', 'data_measure'], keep='first')

mm_grid = (pd.DataFrame({'warehouse': sorted(set(_mm['warehouse']))})
           .merge(pd.DataFrame({'scm_master_category': CATEGORY_COLS}), how='cross')
           .merge(pd.DataFrame({'data_measure': MM_MEASURES}), how='cross'))

df_mm_planning_capacity = mm_grid.merge(
    mm_melted[['warehouse', 'scm_master_category', 'data_measure', 'value']], how='left',
    on=['warehouse', 'scm_master_category', 'data_measure'])
mm_blank = int(df_mm_planning_capacity['value'].isna().sum())
df_mm_planning_capacity['value'] = df_mm_planning_capacity['value'].fillna(0)

# reconciliation
print('warehouses:', _mm['warehouse'].nunique(),
      '| wide columns melted:', len([c for c in _mm.columns if c != 'warehouse']))
print('rows:', len(df_mm_planning_capacity),
      '| expected:', _mm['warehouse'].nunique() * len(CATEGORY_COLS) * len(MM_MEASURES),
      '| duplicate warehouse+category+measure in source:', mm_dupes,
      '| grid cells with no sheet value (0-filled):', mm_blank)
print('columns that would not split on a hyphen:', unparsed)
print('categories in sheet but not in CATEGORY_COLS:', off_cat)
print('measures in sheet but dropped (not in MM_MEASURES):', off_measure)
for m in MM_MEASURES:
    s = df_mm_planning_capacity.loc[df_mm_planning_capacity['data_measure'].eq(m), 'value']
    print(f'  {m:<12} total: {s.sum():>12,.0f} | zero rows: {int(s.eq(0).sum()):>4} / {len(s)}')

if 'df_sto_filtered_latest_date' in globals():
    sto_wh = set(df_sto_filtered_latest_date['warehouse_code'].astype('string').str.strip().dropna())
    mm_wh = set(_mm['warehouse'])
    print('in STO scope but no MM capacity :', sorted(sto_wh - mm_wh))
    print('MM capacity but not in STO scope:', sorted(mm_wh - sto_wh))

df_mm_planning_capacity.head(12)

warehouses: 46 | wide columns melted: 32
rows: 1104 | expected: 1104 | duplicate warehouse+category+measure in source: 0 | grid cells with no sheet value (0-filled): 0
columns that would not split on a hyphen: []
categories in sheet but not in CATEGORY_COLS: []
measures in sheet but dropped (not in MM_MEASURES): ['installation']
  unloading    total:       70,552 | zero rows:    0 / 368
  mm_dispatch  total:       17,396 | zero rows:  248 / 368
  holding      total:      338,179 | zero rows:   68 / 368
in STO scope but no MM capacity : ['FBD', 'PTN', 'SPT']
MM capacity but not in STO scope: ['HSR15', 'MAN_RETAIL_1']

   warehouse scm_master_category data_measure  value
0       AMD2           accessory    unloading    375
1       AMD2           accessory  mm_dispatch      0
2       AMD2           accessory      holding   1295
3       AMD2           furniture    unloading    105
4       AMD2           furniture  mm_dispatch      0
5       AMD2           furniture      holding    161
6       AMD2        office chair    unloading     24
7       AMD2        office chair  mm_dispatch      0
8       AMD2        office chair      holding     44
9       AMD2            mattress    unloading    195
10      AMD2            mattress  mm_dispatch      0
11      AMD2            mattress      holding    357

In [35]:
# https://docs.google.com/spreadsheets/d/1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8/edit
clean_sheet('1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8', 'mm_planning_capacity', range_string="A:D")
write_sheet('1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8', 'mm_planning_capacity', df_mm_planning_capacity)

 Sheet cleared: mm_planning_capacity!A:D
 Written to sheet: mm_planning_capacity

In [36]:
# sofa + flipper-mattress sales by warehouse : last 7 complete days (yesterday back 7 days) -> sheet tab
# https://docs.google.com/spreadsheets/d/1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8/edit
#
# "today" = the IST date. Snowflake's session clock is UTC but order_confirmed_on is stored as IST
# wall-clock time, so a plain CURRENT_DATE() is still yesterday before 05:30 IST and an early-morning
# run would silently drop the latest full day from the 7-day window.

SALES_SHEET_KEY = '1ej_Fbl2qDM74eiw8u9yGRZxJ4LA0xfd3jgwNrkARmX8'
SALES_TAB = 'sofa_flipper_7d_sales'          # <- tab name: change it here if you want another

sofa_flipper_query = """
WITH orders AS (
    SELECT
        o.warehouse,
        DATE(o.order_confirmed_on) AS order_date,
        o.item_sku,
        o.item_quantity
    FROM wakefit_db.public.cartitemlvl_rpt o
    WHERE DATE(o.order_confirmed_on) <  CONVERT_TIMEZONE('Asia/Kolkata', CURRENT_TIMESTAMP())::DATE
      AND DATE(o.order_confirmed_on) >= CONVERT_TIMEZONE('Asia/Kolkata', CURRENT_TIMESTAMP())::DATE - 7
),

products AS (
    SELECT
        item_sku,
        LOWER(scm_master_category) AS scm_master_category,
        LOWER(product_type)        AS product_type
    FROM wakefit_db.crm.wf_products_pricing
)

SELECT
    o.warehouse,
    SUM(CASE WHEN p.scm_master_category = 'sofa'
             THEN o.item_quantity ELSE 0 END)            AS sofa_qty_7d,
    ROUND(SUM(CASE WHEN p.scm_master_category = 'sofa'
             THEN o.item_quantity ELSE 0 END) / 7.0, 2)  AS avg_daily_sofa_qty,

    SUM(CASE WHEN p.scm_master_category = 'mattress'
              AND p.product_type LIKE '%flipper%'
             THEN o.item_quantity ELSE 0 END)            AS flipper_mattress_qty_7d,
    ROUND(SUM(CASE WHEN p.scm_master_category = 'mattress'
              AND p.product_type LIKE '%flipper%'
             THEN o.item_quantity ELSE 0 END) / 7.0, 2)  AS avg_daily_flipper_mattress_qty,

    -- (sofa + flipper) / sofa ; no sofa sales (divide by zero) -> 1
    COALESCE(
        (SUM(CASE WHEN p.scm_master_category = 'sofa'
                  THEN o.item_quantity ELSE 0 END)
       + SUM(CASE WHEN p.scm_master_category = 'mattress'
                   AND p.product_type LIKE '%flipper%'
                  THEN o.item_quantity ELSE 0 END))
       / NULLIF(SUM(CASE WHEN p.scm_master_category = 'sofa'
                         THEN o.item_quantity ELSE 0 END), 0),
        1)                                               AS "total_sofa+flipper/total_sofa"
FROM orders o
JOIN products p
  ON o.item_sku = p.item_sku
WHERE p.scm_master_category = 'sofa'
   OR (p.scm_master_category = 'mattress' AND p.product_type LIKE '%flipper%')
GROUP BY o.warehouse
ORDER BY avg_daily_sofa_qty DESC;
"""
df_sofa_flipper = query_execute(sofa_flipper_query)

# create the tab only if it is not there yet (small grid - set_with_dataframe grows it when needed)
_ss = gc.open_by_key(SALES_SHEET_KEY)
try:
    _ss.worksheet(SALES_TAB)
    print(' Tab exists:', SALES_TAB)
except gspread.WorksheetNotFound:
    _ss.add_worksheet(title=SALES_TAB, rows=100, cols=10)
    print(' Tab created:', SALES_TAB)

# A:F only - the script owns six columns, anything maintained to the right of them survives
clean_sheet(SALES_SHEET_KEY, SALES_TAB, range_string="A:F")
write_sheet(SALES_SHEET_KEY, SALES_TAB, df_sofa_flipper)

# read back : header + one row per warehouse should now be on the sheet
_on_sheet = len(_ss.worksheet(SALES_TAB).col_values(1)) - 1
print('warehouses:', len(df_sofa_flipper), '| rows on sheet:', _on_sheet,
      '| match:', _on_sheet == len(df_sofa_flipper))
print('sofa 7d total:', df_sofa_flipper['sofa_qty_7d'].sum(),
      '| flipper mattress 7d total:', df_sofa_flipper['flipper_mattress_qty_7d'].sum())
print('warehouses with no sofa sales (ratio set to 1):',
      int(df_sofa_flipper['sofa_qty_7d'].fillna(0).eq(0).sum()))
df_sofa_flipper.head(10)

Query executed in schema: SCM
 Tab exists: sofa_flipper_7d_sales
 Sheet cleared: sofa_flipper_7d_sales!A:F
 Written to sheet: sofa_flipper_7d_sales
warehouses: 40 | rows on sheet: 40 | match: True
sofa 7d total: 1368.0 | flipper mattress 7d total: 2073.0
warehouses with no sofa sales (ratio set to 1): 7

,warehouse,sofa_qty_7d,avg_daily_sofa_qty,flipper_mattress_qty_7d,avg_daily_flipper_mattress_qty,total_sofa+flipper/total_sofa
0,DDR,165.0,23.57,107.0,15.29,1.648485
1,HSR6,156.0,22.29,0.0,0.00,1.000000
2,HSR14,150.0,21.43,0.0,0.00,1.000000
3,HYD3,130.0,18.57,261.0,37.29,3.007692
4,DWK2,119.0,17.00,93.0,13.29,1.781513
5,VDR,83.0,11.86,4.0,0.57,1.048193
6,PUN3,73.0,10.43,72.0,10.29,1.986301
7,BLR8,72.0,10.29,223.0,31.86,4.097222
8,MUM,57.0,8.14,168.0,24.00,3.947368
9,CHN2,41.0,5.86,102.0,14.57,3.487805

-----